@extends('layouts.erp-tailwind')

@section('title', (isset($data) ? 'Edit' : 'Tambah') . ' Karyawan - Master')
@section('page-title', 'Karyawan')
@section('page-breadcrumb')
    <span>Master</span><i class="ph ph-caret-right text-[0.55rem]"></i><span>Karyawan</span>
@endsection
@section('dashboard-fullscreen', '1')

@section('content')
@php
    $editing = isset($data);
    $selectedDepartment = old('department', $data->department_id ?? '');
    $selectedPosition = old('position', $data->position_id ?? '');
    $selectedDepartmentName = $selectedDepartment ? (\Modules\Master\Entities\Department::find($selectedDepartment)->name ?? '') : '';
    $selectedPositionName = $selectedPosition ? (\Modules\Master\Entities\Position::find($selectedPosition)->name ?? '') : '';
@endphp
<div class="flex-1 min-h-0 flex flex-col bg-white lg:rounded-2xl lg:border lg:border-gray-100 lg:shadow-sm overflow-hidden">
    <div class="px-5 py-4 border-b border-gray-100 flex items-center justify-between shrink-0">
        <div class="flex items-center gap-3"><a href="{{ route('staff.index') }}" aria-label="Kembali ke karyawan" class="w-9 h-9 rounded-full bg-gray-100 text-gray-600 flex items-center justify-center"><i class="ph-bold ph-arrow-left"></i></a><div><h2 class="text-[15px] font-bold text-gray-900">{{ $editing ? 'Edit Karyawan' : 'Tambah Karyawan' }}</h2><p class="text-[12px] text-gray-400 mt-0.5">{{ $editing ? 'Perbarui data karyawan' : 'Isi data karyawan baru' }}</p></div></div>
    </div>

    <form id="staff-form" action="{{ $editing ? route('staff.update', $data->id) : route('staff.store') }}" method="POST" enctype="multipart/form-data" class="flex-1 min-h-0 flex flex-col">
        @csrf
        @if($editing) @method('PUT') @endif
        <div class="flex-1 min-h-0 overflow-y-auto bg-gray-50/60 px-5 py-5 pb-8 space-y-5">
            @if($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">Periksa kembali data yang ditandai di bawah.</div>@endif
            @if(session('error'))<div role="alert" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{{ session('error') }}</div>@endif
            <div class="flex items-center gap-4"><div class="w-16 h-16 rounded-2xl bg-emerald-50 border border-emerald-100 overflow-hidden flex items-center justify-center text-emerald-700 shrink-0"><img id="staff-avatar-preview" src="{{ $editing && $data->image ? asset('storage/' . $data->image) : '' }}" alt="Pratinjau foto karyawan" class="w-full h-full object-cover {{ $editing && $data->image ? '' : 'hidden' }}"><i id="staff-avatar-placeholder" class="ph ph-user text-2xl {{ $editing && $data->image ? 'hidden' : '' }}"></i></div><div class="flex-1 min-w-0"><label for="avatar" class="text-xs font-semibold text-gray-600 mb-1.5 block">Foto Profil</label><input id="avatar" name="avatar" type="file" accept="image/png,image/jpeg" class="block w-full text-xs text-gray-500 file:mr-3 file:rounded-lg file:border-0 file:bg-emerald-50 file:px-3 file:py-2 file:text-xs file:font-semibold file:text-emerald-700">@error('avatar')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror@if($editing && $data->image)<label class="mt-2 inline-flex items-center gap-2 text-xs text-gray-500"><input type="checkbox" name="avatar_remove" value="1" class="accent-[#0b595b]"> Hapus foto saat ini</label>@endif</div></div>
            <div><label for="staff_name" class="text-xs font-semibold text-gray-600 mb-1.5 block">Nama Karyawan <span class="text-red-400">*</span></label><input id="staff_name" name="staff_name" value="{{ old('staff_name', $data->name ?? '') }}" type="text" required maxlength="255" placeholder="Masukkan nama karyawan" class="w-full h-11 bg-white border {{ $errors->has('staff_name') ? 'border-red-400' : 'border-gray-200' }} rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('staff_name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="nickname" class="text-xs font-semibold text-gray-600 mb-1.5 block">Nama Panggilan <span class="text-red-400">*</span></label><input id="nickname" name="nickname" value="{{ old('nickname', $data->nickname ?? '') }}" type="text" required maxlength="255" placeholder="Masukkan nama panggilan" class="w-full h-11 bg-white border {{ $errors->has('nickname') ? 'border-red-400' : 'border-gray-200' }} rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('nickname')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="nik" class="text-xs font-semibold text-gray-600 mb-1.5 block">NIK</label><input id="nik" name="nik" value="{{ old('nik', $data->nik ?? '') }}" type="text" inputmode="numeric" placeholder="Masukkan NIK" class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('nik')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="contact" class="text-xs font-semibold text-gray-600 mb-1.5 block">No Kontak</label><input id="contact" name="contact" value="{{ old('contact', $data->contact ?? '') }}" type="tel" inputmode="tel" placeholder="Contoh: 081234567890" class="w-full h-11 bg-white border {{ $errors->has('contact') ? 'border-red-400' : 'border-gray-200' }} rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('contact')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="email" class="text-xs font-semibold text-gray-600 mb-1.5 block">E-mail</label><input id="email" name="email" value="{{ old('email', $data->email ?? '') }}" type="email" placeholder="contoh@email.com" class="w-full h-11 bg-white border {{ $errors->has('email') ? 'border-red-400' : 'border-gray-200' }} rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('email')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="gender" class="text-xs font-semibold text-gray-600 mb-1.5 block">Jenis Kelamin</label><select id="gender" name="gender" class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"><option value="">Pilih jenis kelamin</option><option value="male" @selected(old('gender', $data->gender ?? '') === 'male')>Pria</option><option value="female" @selected(old('gender', $data->gender ?? '') === 'female')>Wanita</option></select>@error('gender')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="date_in" class="text-xs font-semibold text-gray-600 mb-1.5 block">Tanggal Masuk</label><input id="date_in" name="date_in" value="{{ old('date_in', $data->date_in ?? '') }}" type="date" class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500">@error('date_in')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div class="border-t border-gray-200 pt-5"><h3 class="text-sm font-bold text-gray-800">Penempatan</h3><p class="text-xs text-gray-400 mt-0.5">Pilih departemen dan jabatan karyawan</p></div>
            <div class="relative" data-staff-picker="department"><label for="department-search" class="text-xs font-semibold text-gray-600 mb-1.5 block">Departemen</label><div class="relative"><input id="department-search" type="text" role="combobox" aria-expanded="false" aria-controls="department-options" autocomplete="off" value="{{ $selectedDepartmentName }}" placeholder="Cari departemen..." class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 pr-10 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"><i class="ph ph-caret-down absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></i></div><input type="hidden" name="department" value="{{ $selectedDepartment }}"><div id="department-options" role="listbox" hidden class="absolute z-30 mt-1 w-full max-h-48 overflow-y-auto rounded-xl border border-gray-200 bg-white shadow-lg"></div>@error('department')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div class="relative" data-staff-picker="position"><label for="position-search" class="text-xs font-semibold text-gray-600 mb-1.5 block">Jabatan</label><div class="relative"><input id="position-search" type="text" role="combobox" aria-expanded="false" aria-controls="position-options" autocomplete="off" value="{{ $selectedPositionName }}" placeholder="Cari jabatan..." class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 pr-10 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"><i class="ph ph-caret-down absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></i></div><input type="hidden" name="position" value="{{ $selectedPosition }}"><div id="position-options" role="listbox" hidden class="absolute z-30 mt-1 w-full max-h-48 overflow-y-auto rounded-xl border border-gray-200 bg-white shadow-lg"></div>@error('position')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label for="status" class="text-xs font-semibold text-gray-600 mb-1.5 block">Status</label><select id="status" name="status" class="w-full h-11 bg-white border border-gray-200 rounded-xl px-4 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"><option value="aktif" @selected(old('status', $data->status ?? 'aktif') === 'aktif')>Aktif</option><option value="nonaktif" @selected(old('status', $data->status ?? 'aktif') === 'nonaktif')>Nonaktif</option></select></div>
            <div><label for="description" class="text-xs font-semibold text-gray-600 mb-1.5 block">Deskripsi</label><textarea id="description" name="description" rows="3" maxlength="1000" placeholder="Deskripsi singkat karyawan" class="w-full bg-white border border-gray-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 resize-none">{{ old('description', $data->description ?? '') }}</textarea>@error('description')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
        </div>
        <div class="shrink-0 bg-white border-t border-gray-100 px-5 pt-4 pb-[calc(1rem+env(safe-area-inset-bottom))] flex items-center gap-3"><a href="{{ route('staff.index') }}" class="flex-1 h-11 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600 flex items-center justify-center">Batal</a><button type="submit" class="flex-1 h-11 rounded-xl bg-[#0b595b] text-white text-sm font-semibold" data-submit>{{ $editing ? 'Simpan Perubahan' : 'Tambah Karyawan' }}</button></div>
    </form>
</div>
@endsection

@include('master::staff.js-create')
